version: "3.5"

services:
  rj-notebook:
      container_name: "rj-notebook-container"
      command: "start-notebook.sh --NotebookApp.token=''"
      image: "jupyter/tensorflow-notebook"
      environment:
        - JUPYTER_ENABLE_LAB=no
      volumes:
        - "./notebooks:/home/jovyan/work"
      expose:
        - "8888"
      restart: always
      networks:
        - rjnet

networks:
  rjnet:
    name: rjnewsite_default