version: "3.5"

services:
  rj-notebook:
      build: .
      container_name: "rj-notebook-container"
      volumes:
        - "./notebooks:/home/jovyan/notebooks"
      expose:
        - "8888"
      restart: always
      networks:
        - rjnet

networks:
  rjnet:
    name: rjnewsite_default