version: "3.5"

services:
  rj-notebook:
      build: .
      container_name: "rj-notebook-container"
      environment:
        - "NB_UID=1003"
        - "GRANT_SUDO=yes"
      expose:
        - "8888"
      restart: always
      networks:
        - rjnet
      user: root
      volumes:
        - "./dependency-lists:/home/jovyan/dependency-lists"
        - "./notebooks:/home/jovyan/work"

networks:
  rjnet:
    name: rjnewsite_default
