version: "3.5"

services:
  rj-notebook:
      build: .
      container_name: "rj-notebook-container"
      environment:
        - "NB_UID=1001"
        - "GRANT_SUDO=yes"
      expose:
        - "8888"
      restart: always
      networks:
        - rjnet
      user: root
      volumes:
        - "./apt-get-requirements.txt:/home/jovyan/apt-get-requirements.txt"
        - "./requirements.txt:/home/jovyan/requirements.txt"
        - "./notebooks:/home/jovyan/work"

networks:
  rjnet:
    name: rjnewsite_default
